// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AccountLoginReqAllOf
 */
export interface AccountLoginReqAllOf {
    /**
     * 用户名
     * @type {string}
     * @memberof AccountLoginReqAllOf
     */
    username?: string;
    /**
     * 密码（加密）
     * @type {string}
     * @memberof AccountLoginReqAllOf
     */
    password?: string;
    /**
     * 验证码
     * @type {string}
     * @memberof AccountLoginReqAllOf
     */
    captcha?: string;
    /**
     * 验证码标识
     * @type {string}
     * @memberof AccountLoginReqAllOf
     */
    uuid?: string;
}


