// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AccountLoginReqAllOf } from './account-login-req-all-of';
import { LoginReq } from './login-req';

/**
 * @type AccountLoginReq
 * 账号登录请求参数
 * @export
 */
export type AccountLoginReq = AccountLoginReqAllOf & LoginReq;



