// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 消费确认响应(审核申请)
 * @export
 * @interface ConsumeResp
 */
export interface ConsumeResp {
    /**
     * 申请ID
     * @type {number}
     * @memberof ConsumeResp
     */
    id?: number;
    /**
     * 消费单号
     * @type {string}
     * @memberof ConsumeResp
     */
    consumeNo?: string;
    /**
     * 会员ID
     * @type {number}
     * @memberof ConsumeResp
     */
    memberId?: number;
    /**
     * 会员姓名
     * @type {string}
     * @memberof ConsumeResp
     */
    memberName?: string;
    /**
     * 门店ID
     * @type {number}
     * @memberof ConsumeResp
     */
    storeId?: number;
    /**
     * 房间ID
     * @type {number}
     * @memberof ConsumeResp
     */
    roomId?: number;
    /**
     * 预定ID
     * @type {number}
     * @memberof ConsumeResp
     */
    reservationId?: number;
    /**
     * 申请人/接待业务员ID
     * @type {number}
     * @memberof ConsumeResp
     */
    applyStaffId?: number;
    /**
     * 接待业务员ID
     * @type {number}
     * @memberof ConsumeResp
     */
    receptionStaffId?: number;
    /**
     * 消费金额
     * @type {number}
     * @memberof ConsumeResp
     */
    consumeAmount?: number;
    /**
     * 使用本金
     * @type {number}
     * @memberof ConsumeResp
     */
    useBalance?: number;
    /**
     * 使用赠送金
     * @type {number}
     * @memberof ConsumeResp
     */
    useGiftAmount?: number;
    /**
     * 状态
     * @type {string}
     * @memberof ConsumeResp
     */
    status?: ConsumeRespStatusEnum;
    /**
     * 审核人ID
     * @type {number}
     * @memberof ConsumeResp
     */
    reviewerId?: number;
    /**
     * 审核时间
     * @type {string}
     * @memberof ConsumeResp
     */
    reviewedAt?: string;
    /**
     * 驳回原因
     * @type {string}
     * @memberof ConsumeResp
     */
    rejectReason?: string;
    /**
     * 备注
     * @type {string}
     * @memberof ConsumeResp
     */
    remark?: string;
    /**
     * 创建时间
     * @type {string}
     * @memberof ConsumeResp
     */
    createdAt?: string;
    /**
     * 更新时间
     * @type {string}
     * @memberof ConsumeResp
     */
    updatedAt?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum ConsumeRespStatusEnum {
    PENDING = 'PENDING',
    APPROVED = 'APPROVED',
    REJECTED = 'REJECTED',
    CANCELLED = 'CANCELLED',
    VOID = 'VOID'
}



