// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 消费确认创建请求
 * @export
 * @interface ConsumeApplyCreateReq
 */
export interface ConsumeApplyCreateReq {
    /**
     * 会员ID
     * @type {number}
     * @memberof ConsumeApplyCreateReq
     */
    memberId: number;
    /**
     * 门店ID
     * @type {number}
     * @memberof ConsumeApplyCreateReq
     */
    storeId: number;
    /**
     * 房间ID
     * @type {number}
     * @memberof ConsumeApplyCreateReq
     */
    roomId?: number;
    /**
     * 预定ID
     * @type {number}
     * @memberof ConsumeApplyCreateReq
     */
    reservationId?: number;
    /**
     * 申请人(接待业务员)ID
     * @type {number}
     * @memberof ConsumeApplyCreateReq
     */
    applyStaffId: number;
    /**
     * 接待业务员ID（不同于申请人时填写）
     * @type {number}
     * @memberof ConsumeApplyCreateReq
     */
    receptionStaffId?: number;
    /**
     * 消费金额
     * @type {number}
     * @memberof ConsumeApplyCreateReq
     */
    consumeAmount: number;
    /**
     * 备注
     * @type {string}
     * @memberof ConsumeApplyCreateReq
     */
    remark?: string;
}


