// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EmailLoginReqAllOf
 */
export interface EmailLoginReqAllOf {
    /**
     * 邮箱
     * @type {string}
     * @memberof EmailLoginReqAllOf
     */
    email?: string;
    /**
     * 验证码
     * @type {string}
     * @memberof EmailLoginReqAllOf
     */
    captcha?: string;
}


