// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * H5 卡类型
 * @export
 * @interface H5CardTypeResp
 */
export interface H5CardTypeResp {
    /**
     * 卡类型ID
     * @type {number}
     * @memberof H5CardTypeResp
     */
    id?: string;
    /**
     * 名称
     * @type {string}
     * @memberof H5CardTypeResp
     */
    name?: string;
    /**
     * 备注
     * @type {string}
     * @memberof H5CardTypeResp
     */
    remark?: string;
    /**
     * 状态
     * @type {number}
     * @memberof H5CardTypeResp
     */
    status?: number;
}


