// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * H5 新增客户请求
 * @export
 * @interface H5MemberCreateReq
 */
export interface H5MemberCreateReq {
    /**
     * 卡类型ID
     * @type {number}
     * @memberof H5MemberCreateReq
     */
    cardTypeId?: string;
    /**
     * 姓名
     * @type {string}
     * @memberof H5MemberCreateReq
     */
    name: string;
    /**
     * 手机号
     * @type {string}
     * @memberof H5MemberCreateReq
     */
    phone: string;
    /**
     * 身份证号
     * @type {string}
     * @memberof H5MemberCreateReq
     */
    idCard?: string;
    /**
     * 备注（绑定关系备注）
     * @type {string}
     * @memberof H5MemberCreateReq
     */
    remark?: string;
}


