// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * H5 客户响应
 * @export
 * @interface H5MemberResp
 */
export interface H5MemberResp {
    /**
     * 会员ID
     * @type {number}
     * @memberof H5MemberResp
     */
    id?: string;
    /**
     * 会员姓名
     * @type {string}
     * @memberof H5MemberResp
     */
    name?: string;
    /**
     * 手机号
     * @type {string}
     * @memberof H5MemberResp
     */
    phone?: string;
    /**
     * 会员卡号
     * @type {string}
     * @memberof H5MemberResp
     */
    cardNo?: string;
    /**
     * 卡类型ID
     * @type {number}
     * @memberof H5MemberResp
     */
    cardTypeId?: string;
    /**
     * 卡类型名称
     * @type {string}
     * @memberof H5MemberResp
     */
    cardTypeName?: string;
    /**
     * 余额
     * @type {number}
     * @memberof H5MemberResp
     */
    balance?: number;
    /**
     * 赠送余额
     * @type {number}
     * @memberof H5MemberResp
     */
    giftBalance?: number;
    /**
     * 状态
     * @type {number}
     * @memberof H5MemberResp
     */
    status?: number;
    /**
     * 绑定门店ID
     * @type {number}
     * @memberof H5MemberResp
     */
    storeId?: string;
    /**
     * 绑定门店名称
     * @type {string}
     * @memberof H5MemberResp
     */
    storeName?: string;
    /**
     * 负责业务员ID
     * @type {number}
     * @memberof H5MemberResp
     */
    staffId?: string;
    /**
     * 负责业务员姓名
     * @type {string}
     * @memberof H5MemberResp
     */
    staffName?: string;
    /**
     * 创建时间
     * @type {string}
     * @memberof H5MemberResp
     */
    createdAt?: string;
    /**
     * 更新时间
     * @type {string}
     * @memberof H5MemberResp
     */
    updatedAt?: string;
}


