// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * H5 新增业务员请求
 * @export
 * @interface H5StaffCreateReq
 */
export interface H5StaffCreateReq {
    /**
     * 登录用户名
     * @type {string}
     * @memberof H5StaffCreateReq
     */
    username: string;
    /**
     * 密码
     * @type {string}
     * @memberof H5StaffCreateReq
     */
    password: string;
    /**
     * 姓名
     * @type {string}
     * @memberof H5StaffCreateReq
     */
    name: string;
    /**
     * 手机号
     * @type {string}
     * @memberof H5StaffCreateReq
     */
    phone: string;
    /**
     * 微信号
     * @type {string}
     * @memberof H5StaffCreateReq
     */
    wechat?: string;
}


