// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * H5 团队成员响应
 * @export
 * @interface H5TeamStaffResp
 */
export interface H5TeamStaffResp {
    /**
     * 员工ID
     * @type {number}
     * @memberof H5TeamStaffResp
     */
    id?: number;
    /**
     * 姓名
     * @type {string}
     * @memberof H5TeamStaffResp
     */
    name?: string;
    /**
     * 手机号
     * @type {string}
     * @memberof H5TeamStaffResp
     */
    phone?: string;
    /**
     * 门店ID
     * @type {number}
     * @memberof H5TeamStaffResp
     */
    storeId?: number;
    /**
     * 门店名称
     * @type {string}
     * @memberof H5TeamStaffResp
     */
    storeName?: string;
    /**
     * 状态
     * @type {number}
     * @memberof H5TeamStaffResp
     */
    status?: number;
    /**
     * 创建时间
     * @type {string}
     * @memberof H5TeamStaffResp
     */
    createdAt?: string;
    /**
     * 更新时间
     * @type {string}
     * @memberof H5TeamStaffResp
     */
    updatedAt?: string;
}


