// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 登录响应
 * @export
 * @interface LoginResp
 */
export interface LoginResp {
    /**
     * Token
     * @type {string}
     * @memberof LoginResp
     */
    token?: string;
}


