// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 登录请求参数基类
 * @export
 * @interface LoginReq
 */
export interface LoginReq {
    /**
     * 客户端 ID
     * @type {string}
     * @memberof LoginReq
     */
    clientId: string;
    /**
     * 认证类型<span style=\'color:red\'>{ACCOUNT=账号, EMAIL=邮箱, PHONE=手机号, SOCIAL=第三方账号, EMAIL_CODE=邮箱验证码, MAGIC_LINK=魔法链接}</span>
     * @type {string}
     * @memberof LoginReq
     */
    authType: LoginReqAuthTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum LoginReqAuthTypeEnum {
    ACCOUNT = 'ACCOUNT',
    EMAIL = 'EMAIL',
    PHONE = 'PHONE',
    SOCIAL = 'SOCIAL',
    EMAILCODE = 'EMAIL_CODE',
    MAGICLINK = 'MAGIC_LINK'
}



