// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { LoginReq } from './login-req';
import { PhoneLoginReqAllOf } from './phone-login-req-all-of';

/**
 * @type PhoneLoginReq
 * 手机号登录请求参数
 * @export
 */
export type PhoneLoginReq = LoginReq & PhoneLoginReqAllOf;



