// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 充值审核请求
 * @export
 * @interface RechargeReviewReq
 */
export interface RechargeReviewReq {
    /**
     * 充值申请ID
     * @type {number}
     * @memberof RechargeReviewReq
     */
    id: number;
    /**
     * 审核人(队长)ID
     * @type {number}
     * @memberof RechargeReviewReq
     */
    reviewerId: number;
    /**
     * 拒绝原因
     * @type {string}
     * @memberof RechargeReviewReq
     */
    reason?: string;
}


