// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 充值申请响应
 * @export
 * @interface RechargeResp
 */
export interface RechargeResp {
    /**
     * 申请ID
     * @type {number}
     * @memberof RechargeResp
     */
    id?: number;
    /**
     * 申请单号
     * @type {string}
     * @memberof RechargeResp
     */
    applyNo?: string;
    /**
     * 会员ID
     * @type {number}
     * @memberof RechargeResp
     */
    memberId?: number;
    /**
     * 会员姓名
     * @type {string}
     * @memberof RechargeResp
     */
    memberName?: string;
    /**
     * 会员卡号
     * @type {string}
     * @memberof RechargeResp
     */
    cardNo?: string;
    /**
     * 门店ID
     * @type {number}
     * @memberof RechargeResp
     */
    storeId?: number;
    /**
     * 申请人(业务员)ID
     * @type {number}
     * @memberof RechargeResp
     */
    staffId?: number;
    /**
     * 本金
     * @type {number}
     * @memberof RechargeResp
     */
    amount?: number;
    /**
     * 赠送金
     * @type {number}
     * @memberof RechargeResp
     */
    giftAmount?: number;
    /**
     * 状态
     * @type {string}
     * @memberof RechargeResp
     */
    status?: RechargeRespStatusEnum;
    /**
     * 审核人ID
     * @type {number}
     * @memberof RechargeResp
     */
    reviewerId?: number;
    /**
     * 审核时间
     * @type {string}
     * @memberof RechargeResp
     */
    reviewedAt?: string;
    /**
     * 拒绝原因
     * @type {string}
     * @memberof RechargeResp
     */
    rejectReason?: string;
    /**
     * 充值凭证URL列表
     * @type {Array<string>}
     * @memberof RechargeResp
     */
    voucherUrls?: Array<string>;
    /**
     * 备注
     * @type {string}
     * @memberof RechargeResp
     */
    remark?: string;
    /**
     * 创建时间
     * @type {string}
     * @memberof RechargeResp
     */
    createdAt?: string;
    /**
     * 更新时间
     * @type {string}
     * @memberof RechargeResp
     */
    updatedAt?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum RechargeRespStatusEnum {
    PENDING = 'PENDING',
    APPROVED = 'APPROVED',
    REJECTED = 'REJECTED',
    CANCELLED = 'CANCELLED',
    VOID = 'VOID'
}



