// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 预定取消请求
 * @export
 * @interface ReservationCancelReq
 */
export interface ReservationCancelReq {
    /**
     * 预定ID
     * @type {number}
     * @memberof ReservationCancelReq
     */
    id: number;
    /**
     * 取消人ID
     * @type {number}
     * @memberof ReservationCancelReq
     */
    staffId: number;
    /**
     * 取消原因
     * @type {string}
     * @memberof ReservationCancelReq
     */
    reason?: string;
}


