// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 预定创建请求
 * @export
 * @interface ReservationCreateReq
 */
export interface ReservationCreateReq {
    /**
     * 门店ID
     * @type {number}
     * @memberof ReservationCreateReq
     */
    storeId: number;
    /**
     * 房间ID
     * @type {number}
     * @memberof ReservationCreateReq
     */
    roomId: number;
    /**
     * 会员ID
     * @type {number}
     * @memberof ReservationCreateReq
     */
    memberId: number;
    /**
     * 申请人(业务员)ID
     * @type {number}
     * @memberof ReservationCreateReq
     */
    staffId: number;
    /**
     * 预定日期 yyyy-MM-dd
     * @type {string}
     * @memberof ReservationCreateReq
     */
    reserveDate: string;
    /**
     * 开始时间（当天分钟，0-1439），不传默认0
     * @type {number}
     * @memberof ReservationCreateReq
     */
    startMin?: number;
    /**
     * 结束时间（当天分钟，1-1440），不传默认1440
     * @type {number}
     * @memberof ReservationCreateReq
     */
    endMin?: number;
    /**
     * 预计人数
     * @type {number}
     * @memberof ReservationCreateReq
     */
    guestCount?: number;
    /**
     * 备注
     * @type {string}
     * @memberof ReservationCreateReq
     */
    remark?: string;
}


