// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 预定响应
 * @export
 * @interface ReservationResp
 */
export interface ReservationResp {
    /**
     * 预定ID
     * @type {number}
     * @memberof ReservationResp
     */
    id?: number;
    /**
     * 预定号
     * @type {string}
     * @memberof ReservationResp
     */
    reserveNo?: string;
    /**
     * 门店ID
     * @type {number}
     * @memberof ReservationResp
     */
    storeId?: number;
    /**
     * 房间ID
     * @type {number}
     * @memberof ReservationResp
     */
    roomId?: number;
    /**
     * 会员ID
     * @type {number}
     * @memberof ReservationResp
     */
    memberId?: number;
    /**
     * 申请人(业务员)ID
     * @type {number}
     * @memberof ReservationResp
     */
    staffId?: number;
    /**
     * 预定日期
     * @type {string}
     * @memberof ReservationResp
     */
    reserveDate?: string;
    /**
     * 预计人数
     * @type {number}
     * @memberof ReservationResp
     */
    guestCount?: number;
    /**
     * 状态
     * @type {string}
     * @memberof ReservationResp
     */
    status?: ReservationRespStatusEnum;
    /**
     * 审核人ID
     * @type {number}
     * @memberof ReservationResp
     */
    reviewerId?: number;
    /**
     * 审核时间
     * @type {string}
     * @memberof ReservationResp
     */
    reviewedAt?: string;
    /**
     * 取消人ID
     * @type {number}
     * @memberof ReservationResp
     */
    cancelledByStaffId?: number;
    /**
     * 取消原因
     * @type {string}
     * @memberof ReservationResp
     */
    cancelReason?: string;
    /**
     * 备注
     * @type {string}
     * @memberof ReservationResp
     */
    remark?: string;
    /**
     * 创建时间
     * @type {string}
     * @memberof ReservationResp
     */
    createdAt?: string;
    /**
     * 更新时间
     * @type {string}
     * @memberof ReservationResp
     */
    updatedAt?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum ReservationRespStatusEnum {
    PENDING = 'PENDING',
    APPROVED = 'APPROVED',
    REJECTED = 'REJECTED',
    CANCELLED = 'CANCELLED'
}



