// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 响应信息
 * @export
 * @interface RObject
 */
export interface RObject {
    /**
     * 状态码
     * @type {string}
     * @memberof RObject
     */
    code?: string;
    /**
     * 状态信息
     * @type {string}
     * @memberof RObject
     */
    msg?: string;
    /**
     * 是否成功
     * @type {boolean}
     * @memberof RObject
     */
    success?: boolean;
    /**
     * 时间戳
     * @type {number}
     * @memberof RObject
     */
    timestamp?: number;
    /**
     * 响应数据
     * @type {object}
     * @memberof RObject
     */
    data?: object;
}


