// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { RoomScheduleBookingResp } from './room-schedule-booking-resp';

/**
 * 房间行
 * @export
 * @interface RoomScheduleRoomResp
 */
export interface RoomScheduleRoomResp {
    /**
     * 房间ID
     * @type {number}
     * @memberof RoomScheduleRoomResp
     */
    id?: number;
    /**
     * 门店ID
     * @type {number}
     * @memberof RoomScheduleRoomResp
     */
    storeId?: number;
    /**
     * 房名
     * @type {string}
     * @memberof RoomScheduleRoomResp
     */
    roomName?: string;
    /**
     * 房号
     * @type {string}
     * @memberof RoomScheduleRoomResp
     */
    roomNo?: string;
    /**
     * 房型
     * @type {string}
     * @memberof RoomScheduleRoomResp
     */
    roomType?: string;
    /**
     * 房间价格
     * @type {number}
     * @memberof RoomScheduleRoomResp
     */
    price?: number;
    /**
     * 房间状态
     * @type {number}
     * @memberof RoomScheduleRoomResp
     */
    status?: number;
    /**
     * 按日期的预订信息，key为yyyy-MM-dd
     * @type {{ [key: string]: RoomScheduleBookingResp; }}
     * @memberof RoomScheduleRoomResp
     */
    bookings?: { [key: string]: RoomScheduleBookingResp; };
}


