// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { RoomScheduleRoomResp } from './room-schedule-room-resp';

/**
 * 排房/房态日历响应
 * @export
 * @interface RoomScheduleResp
 */
export interface RoomScheduleResp {
    /**
     * 开始日期 yyyy-MM-dd
     * @type {string}
     * @memberof RoomScheduleResp
     */
    startDate?: string;
    /**
     * 结束日期 yyyy-MM-dd
     * @type {string}
     * @memberof RoomScheduleResp
     */
    endDate?: string;
    /**
     * 日期列表
     * @type {Array<string>}
     * @memberof RoomScheduleResp
     */
    dates?: Array<string>;
    /**
     * 房间列表
     * @type {Array<RoomScheduleRoomResp>}
     * @memberof RoomScheduleResp
     */
    rooms?: Array<RoomScheduleRoomResp>;
}


