// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { SocialAuthAuthorizeResp } from './social-auth-authorize-resp';

/**
 * 响应信息
 * @export
 * @interface RSocialAuthAuthorizeResp
 */
export interface RSocialAuthAuthorizeResp {
    /**
     * 状态码
     * @type {string}
     * @memberof RSocialAuthAuthorizeResp
     */
    code?: string;
    /**
     * 状态信息
     * @type {string}
     * @memberof RSocialAuthAuthorizeResp
     */
    msg?: string;
    /**
     * 是否成功
     * @type {boolean}
     * @memberof RSocialAuthAuthorizeResp
     */
    success?: boolean;
    /**
     * 时间戳
     * @type {number}
     * @memberof RSocialAuthAuthorizeResp
     */
    timestamp?: number;
    /**
     * 
     * @type {SocialAuthAuthorizeResp}
     * @memberof RSocialAuthAuthorizeResp
     */
    data?: SocialAuthAuthorizeResp;
}


