// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SocialLoginReqAllOf
 */
export interface SocialLoginReqAllOf {
    /**
     * 第三方登录平台
     * @type {string}
     * @memberof SocialLoginReqAllOf
     */
    source?: string;
    /**
     * 授权码
     * @type {string}
     * @memberof SocialLoginReqAllOf
     */
    code?: string;
    /**
     * 状态码
     * @type {string}
     * @memberof SocialLoginReqAllOf
     */
    state?: string;
}


