// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { LoginReq } from './login-req';
import { SocialLoginReqAllOf } from './social-login-req-all-of';

/**
 * @type SocialLoginReq
 * 第三方账号登录请求参数
 * @export
 */
export type SocialLoginReq = LoginReq & SocialLoginReqAllOf;



