// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 三方账号授权认证响应参数
 * @export
 * @interface SocialAuthAuthorizeResp
 */
export interface SocialAuthAuthorizeResp {
    /**
     * 授权 URL
     * @type {string}
     * @memberof SocialAuthAuthorizeResp
     */
    authorizeUrl?: string;
}


