// tslint:disable
/**
 * geo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * H5 门店简单响应
 * @export
 * @interface StoreSimpleResp
 */
export interface StoreSimpleResp {
    /**
     * 门店ID
     * @type {number}
     * @memberof StoreSimpleResp
     */
    id?: string;
    /**
     * 门店名称
     * @type {string}
     * @memberof StoreSimpleResp
     */
    name?: string;
}


